PACKAGE_NAME="astral-hwmon"
PACKAGE_VERSION="0.3.0"
BUILT_MODULE_NAME[0]="astral-hwmon"
BUILT_MODULE_LOCATION[0]="driver"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/driver modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/driver clean"
AUTOINSTALL="yes"
